version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./php/src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./php/src:/var/www/html
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: pega_nomes
      MYSQL_USER: root
      MYSQL_PASSWORD: secreta
  db:
    image: mysql:latest
    command: "--init-file /docker-entrypoint-initdb.d/banco_dados/init.sql"
    environment:
      MYSQL_ROOT_PASSWORD: secreta
      MYSQL_DATABASE: pega_nomes
    volumes:
      - ./banco_dados/data:/var/lib/mysql
      - ./banco_dados/init.sql:/docker-entrypoint-initdb.d/banco_dados/init.sql
    ports:
      - "3306:3306"
